### ISSUE TITLE
test it

### ISSUE THREAD

**Issue by akwatra** [rockstarcode/Streamline#1]
you mention:

The only way to test this app is using a web server capable of threading PHP executions.
which web server are you referring. 

you did good job, but all waste of car made with not available fuel. no use of. 

you mean to say we could not use in production ? 

Please try to test yourself ready to production level, as you an do fast,' 
then other outside project coder like us. 

when a project in doubt from start ... how should any one takeoff with ...

**Comment by 82rules** [comment]
I'm not quite sure what the issue is, I covered basic functionality in the unit tests available here. https://travis-ci.org/rockstarcode/Streamline, I didn't aim nor intend to provide a guarantee for the project. 

It's designed for you to incorporate into your own infrastructure, it's not a stand alone service with SLA's. 

But I'd welcome any PR to further increase code coverage but I have no plans on spending time building more test cases for this library at this time. 

To answer your question: In order to test this library you need to be able to create various sessions where execution can talk to other sessions via pub/sub, you can't really test this procedural.
